version: '3'
services:
  app:
    build:
      context: .
      args:
        - CODECOV_TOKEN=$CODECOV_TOKEN
    image: smooch-jwt
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    command: npm start