version: '3.5'
services:
  smooch-jwt:
    build:
      context: .
      cache_from:
        - smooch-jwt
      args:
        - CODECOV_TOKEN=$CODECOV_TOKEN
    image: gcr.io/zip-zap-gateway/smooch-jwt
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    command: npm start